### PR TITLE
Update styling for word list

### PR DESCRIPTION
**Pull request by rolfheij-sil**
Small fix to the look and feel of the word list extension.

image

image

Add nice spinning loader thingy

image

This change is [Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
The loader looks so cool, thanks Rolf!

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-:-O7Zh9zH9EDOnk3EUqYU:b7em13j)* status: all files reviewed, 2 unresolved discussions (waiting on @rolfheij-sil)

___
*[`src/paratext-bible-word-list/src/word-list.web-view.scss` line 12 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-O7ZgFi2CxEpdeXgXM6S:-O7ZgFi2CxEpdeXgXM6T:b4wos5m) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/101446adcecd2df1d5a875ef32970604a40b599d/src/paratext-bible-word-list/src/word-list.web-view.scss#L12)):*
> ```SCSS
> #root {
>   height: 100%;
> }
> ```

If you add these elements it styles globally right, affecting the whole app? Is that what we want? 



_Code quote:_
```SCSS
html {
  height: 100%;
}

body {
  height: 100%;
  margin: 0;
}

#root {
  height: 100%;
}
```
___
*[`src/paratext-bible-word-list/src/word-list.web-view.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-O7ZfKfZ7qnMhy57B824:-O7ZfKfZ7qnMhy57B825:b-28864l) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/101446adcecd2df1d5a875ef32970604a40b599d/src/paratext-bible-word-list/src/word-list.web-view.tsx#L9)):*
> ```XML
>   Label,
>   ScriptureReference,
>   ShadCnSwitch,
> ```

Can we get rid of the MUI Switch now, and just call this Switch?

**Review by rolfheij-sil — COMMENTED** [review]
Thanks! :)

> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-:-O7_phfWDxX5iPIM50dB:b-7z430k)* status: all files reviewed, 2 unresolved discussions (waiting on @jolierabideau)

___
*[`src/paratext-bible-word-list/src/word-list.web-view.scss` line 12 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-O7ZgFi2CxEpdeXgXM6S:-O7_pn-G-px-2WwC3R5b:br5xklf) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/101446adcecd2df1d5a875ef32970604a40b599d/src/paratext-bible-word-list/src/word-list.web-view.scss#L12)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

If you add these elements it styles globally right, affecting the whole app? Is that what we want?
</blockquote></details>

It affects this entire webview, since that's essentially it's own HTML document. So this should be okay. We've done a similar thing in `extensions\src\platform-scripture\src\inventory.web-view.scss`
___
*[`src/paratext-bible-word-list/src/word-list.web-view.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-O7ZfKfZ7qnMhy57B824:-O7_qkb78PCJ5I78_75_:bf5xtj3) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/101446adcecd2df1d5a875ef32970604a40b599d/src/paratext-bible-word-list/src/word-list.web-view.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Can we get rid of the MUI Switch now, and just call this Switch?
</blockquote></details>

I'd like to do that, but it might be better to do it all in one go. Rip out all MUI stuff and fix everything that breaks. Might be a good idea to bring this up in tomorrows sprint meetings

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/paratext-bible-word-list/src/word-list.web-view.tsx` line 9 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41#-O7ZfKfZ7qnMhy57B824:-O7dHUwm1pF_2hmb64LI:b-896fix) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/101446adcecd2df1d5a875ef32970604a40b599d/src/paratext-bible-word-list/src/word-list.web-view.tsx#L9)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Good idea to bring it up, I've gotten rid of a few as I come across them
</blockquote></details>

Done.

**Review by jolierabideau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
