### PR TITLE
Spanish localizations

### PR DESCRIPTION
**Pull request by katherinejensen00**
Adding some localizations and making small fixes.

- - -
This change is [Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48)

### CODE REVIEW

**Review by jolierabideau — CHANGES_REQUESTED** [review]
Thanks Katherine!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48#-:-OC4rTV83nCsUIcVu6tN:b-fv84fq)* status: all files reviewed, 1 unresolved discussion (waiting on @katherinejensen00)

___
*[`src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48#-OC4rHS5EjJu32s8QY2K:-OC4rHS5EjJu32s8QY2L:bd4hl9j) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/90aaa45fa2dc8f915e4e44bcbd106631e3f60f2d/src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx#L47)):*
> ```XML
>     useMemo(
>       () => [selectProjectsTitleKey, selectProjectsPromptKey, selectProjectsKey, textCollectionKey],
>       [],
> ```

Do these keys not need to be in the dependency array?

**Review by katherinejensen00 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48)* status: all files reviewed, 1 unresolved discussion (waiting on @jolierabideau)

___
*[`src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx` line 47 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48#-OC4rHS5EjJu32s8QY2K:-OC51gtw9AnrlkoVFTEa:bh91j9v) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/90aaa45fa2dc8f915e4e44bcbd106631e3f60f2d/src/paratext-bible-text-collection/src/web-views/paratext-text-collection.web-view.tsx#L47)):*
<details><summary><i>Previously, jolierabideau wrote…</i></summary><blockquote>

Do these keys not need to be in the dependency array?
</blockquote></details>


They aren't going to change, but it doesn't hurt to add them so I went ahead and did that.

**Review by jolierabideau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @katherinejensen00)

**Review by jolierabideau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/48)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @katherinejensen00)

**Pull request merged**
