### PR TITLE
Remove RefSelector and use new Table and DataTable

### PR DESCRIPTION
**Pull request by rolfheij-sil**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27)

### CODE REVIEW

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[`src/paratext-bible-word-list/src/word-table.component.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27#-O1I7tKwCSde25c8KptY:-O1I7tKwCSde25c8KptZ:bhthbi) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/4d558238810b1bfcb106767ea110e63ab96bc08d/src/paratext-bible-word-list/src/word-table.component.tsx#L4)):*
> ```XML
> import { Button, DataTable } from 'platform-bible-react';
> import type { WordListEntry } from 'paratext-bible-word-list';
> import { ColumnDef, Row, SortDirection } from '@tanstack/react-table';
> ```

If we decide to move features like these inside the DataTable component as per [this question/to-do](https://github.com/paranext/paranext-core/pull/914/files#diff-b6d720f3f45ea36080814f8a86f7bec93e20fdc92f56b80b224d34d99c04cd44R11), installing `@tanstack/react-table` might not be necessary in this repo

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27#-:-O27GFvy5T4yQ6L-bimL:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by rolfheij-sil — COMMENTED** [review]
Thanks for reviewing, Ira. I indentified a dependency issue that I have now resolved. Would you be so kind to review again? Thanks!

> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27#-:-O29i7Ks1_uTUe4mYdDr:b7nsobr)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

**Review by rolfheij-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @irahopkinson)

___
*[`src/paratext-bible-word-list/src/word-table.component.tsx` line 4 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27#-O1I7tKwCSde25c8KptY:-O29iQJzB-RSdbklKnJs:b4ifot4) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/4d558238810b1bfcb106767ea110e63ab96bc08d/src/paratext-bible-word-list/src/word-table.component.tsx#L4)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

If we decide to move features like these inside the DataTable component as per [this question/to-do](https://github.com/paranext/paranext-core/pull/914/files#diff-b6d720f3f45ea36080814f8a86f7bec93e20fdc92f56b80b224d34d99c04cd44R11), installing `@tanstack/react-table` might not be necessary in this repo
</blockquote></details>

The features have been moved into DataTable, imports have been updated accordingly, and @tanstack/react-table has been removed from the list of dependencies

**Review by irahopkinson — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/27#-:-O29ot5T3V_EPWevb5CA:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rolfheij-sil)

**Pull request merged**
