### PR TITLE
allow theming + fix dark mode

### PR DESCRIPTION
**Pull request by Sebastian-ubs**
This change is [Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34)

### CODE REVIEW

**Review by rolfheij-sil — CHANGES_REQUESTED** [review]
Nice. One small typo is all I see

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34#-:-O6WUgwS8ZnEIOl0Tc-O:b-duxlms)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

___
*[`src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss` line 20 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34#-O6WUcT0BlIQ_XtRfLDa:-O6WUcT0BlIQ_XtRfLDb:b-c9dv6p) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/d9feb006c88d8b5ef32b18626f8edf5444a53465/src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss#L20)):*
> ```SCSS
> }
> 
> // CAUTION: Keep in sync withhttps://github.com/paranext/paranext-core/blob/main/extensions/src/platform-scripture-editor/src/_editor-overrides.scss
> ```

withhttps needs a whitespace

**Review by tjcouch-sil — DISMISSED** [review]
:lgtm: with that typo fixed, this looks great! Thanks!

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34#-:-O6WcLsb-tSMfaP_0awx:b-d79mxs)* status: all files reviewed, 1 unresolved discussion (waiting on @Sebastian-ubs)

**Review by tjcouch-sil — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @rolfheij-sil)

___
*[`src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss` line 20 at r1](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34#-O6WUcT0BlIQ_XtRfLDa:-O6WszKCCS8Zi-B6sBCH:b-886gsx) ([raw file](https://github.com/paranext/paratext-bible-extensions/blob/d9feb006c88d8b5ef32b18626f8edf5444a53465/src/paratext-bible-text-collection/src/web-views/editor-styles/_editor-overrides.scss#L20)):*
<details><summary><i>Previously, rolfheij-sil (Rolf Heij) wrote…</i></summary><blockquote>

withhttps needs a whitespace
</blockquote></details>

Fixed

**Review by rolfheij-sil — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by rolfheij-sil — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34#-:-O6X6Gr543Rxo4YjOrxo:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @tjcouch-sil)

**Review by tjcouch-sil — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/paranext/paratext-bible-extensions/34)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Sebastian-ubs)

**Pull request merged**
